nota1=float(input("Qual a sua nota fih?"))
nota2=float(input("Qual sua nota fih?"))
nota3=float(input("Qual sua nota fih!"))
soma=float(nota1 + nota2 + nota3)
media=float(soma/3)
nota4=float(input("Qual sua nota fih?"))
soma2=float(nota1 + nota2 + nota3 + nota4)
media2=float(soma2/4)
print("A media das 3 notas é " + str(media) + " ja a media das 4 notas é " + str(media2))
