valor=float(input("Qual o valor do produto fih?"))
des=float(input("Quanto de desconto fih?"))
des2=float(des/100)
des3=float(valor-(valor*des2))
print("O produto custava " + str(valor) + " Foi aplicado um desconto de " + str(des) + " e o valor final ficou " + str(des3))