peso=float(input("Qual e o seu peso fih?"))
sand=float(input("Quantos sanduiches voce comeu fih?"))
sand2=float(sand * 0.100)
peso2=float(sand2+peso)
sand3=float(8.50)
sand4=float(sand*sand3)
print("Os quilos engordados foram " + str(peso2) + " foram gastados ao mes " + str(sand4))
