sal=float(input("Qual o seu salario fih? \n"))
f=float(sal +(sal*1.33))
a=float(sal+(sal*0.74))
p=float(sal+(sal*1.45))
print("Baseado no seu salario suas férias seriam " + str(f) + " seu bônus seria " + str(a) + " e caso você fosse promovida seria  " + str(p))