real=float(input("Quantos reais tu tem na conta fih?"))
dolar=float(real * 5.64)
euro=float(real*6.41)
yene=float(real*0.039)
print("O " + str(real) + " na sua conta em dolars seria " + str(dolar) + " ja em euros " + str(euro) + " ja em yene " + str(yene))