peso=float(input("Quanto voce pesa fih? \n"))
dias=float(input("Quantos dias voce vai na academia fih? \n"))
massa=float(dias*0.20)
perda=float(dias*0.40)
total=float(peso+massa-perda)
print("Voce pessava " + str(peso) + " e perdeu " + str(perda) + " de massa gorda porem ganhou " + str(massa)+ " de massa muscular, pesando hoje " + str(total))