km=float(input("Quantos km esta rodando fih? \n"))
hec=float(km*10)
dec=float(km*100)
met=float(km*1000)
cm=float(km*100000)
mil=float(km*1000000)
print("Voce digitou " + str(km) + " :km \n" + str(hec) + " :hec \n" + str(dec) + " :dec \n" + str(met) + " :met \n" + str(cm) + " :cm\n" + str(mil) + " :mil ")