div=int(input("Qual sua divida fih?"))
temp=int(input("Quanto tempo voce esta com essa divida fih?"))
taxa=int(input("Quanto é a sua taxa fih?"))
juros=int(div*temp*taxa)
total=int(juros+div)
print("Os juros são " + str(juros) + " e a dvida total é " + str(total))
